# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SpaTimeClusCpp <- function(input, inputparam, matT, toollogistic) {
    .Call('SpaTimeClus_SpaTimeClusCpp', PACKAGE = 'SpaTimeClus', input, inputparam, matT, toollogistic)
}

