// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SpaTimeClusCpp
S4 SpaTimeClusCpp(S4 input, List inputparam, NumericMatrix matT, NumericMatrix toollogistic);
RcppExport SEXP SpaTimeClus_SpaTimeClusCpp(SEXP inputSEXP, SEXP inputparamSEXP, SEXP matTSEXP, SEXP toollogisticSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type input(inputSEXP);
    Rcpp::traits::input_parameter< List >::type inputparam(inputparamSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type matT(matTSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type toollogistic(toollogisticSEXP);
    __result = Rcpp::wrap(SpaTimeClusCpp(input, inputparam, matT, toollogistic));
    return __result;
END_RCPP
}
